_target_: open_universe.dataset_aligned.WordCutDataModule   # new DM class

batch_size: 4        # keep a single global knob; mode/fixed_len no longer used
                     # (each sample is always win_len_sec)


train:
  dataset: vb-train-word
  dl_opts: {batch_size: 4, num_workers: 12, pin_memory: true, shuffle: true}
val:
  dataset: vb-val-word
  dl_opts: {batch_size: 1, num_workers: 4,  pin_memory: true, shuffle: false}
test:
  dataset: vb-val-word
  dl_opts: {batch_size: 1, num_workers: 4,  pin_memory: true, shuffle: false}

datasets:
  vb-train-word:
    _target_: open_universe.dataset_aligned.WordCutDataset
    audio_root: data/voicebank_demand/16k
    textgrid_root: data/voicebank_demand/textgrids          # pre‑computed TextGrids
    split: train
    fs: 16000
    win_len_sec: 2.0 # 2.0
    min_cut_sec: 0.5 # 1.0
    max_cut_sec: 2.0 # 2.0
    num_samples_per_audio: 1
    repeat_sample: true
    part_used: 1.0
    

  vb-val-word:
    _target_: open_universe.dataset_aligned.WordCutDataset
    audio_root: ${..vb-train-word.audio_root}
    textgrid_root: ${..vb-train-word.textgrid_root}
    split: val
    fs: 16000
    win_len_sec: 2.0          # still needed for mask length
    num_samples_per_audio: 1
    repeat_sample: false
    part_used: 1.0