_target_: open_universe.datasets.DataModule

# ---------------- global batching switches --------------------------- #
mode: bucket_bs         # fixed | bucket_bs | bucket_budget
fixed_len_sec: 4.0          # only for mode=fixed
batch_size: 4               # for fixed / bucket_bs
budget_sec: 12.0 # 12.0     # for bucket_budget # 12.0 good for local
width_pct: 0.05 # 0.05             # bucket tolerance (fallback)
width_sec: null # 0.25             # (use one or the other)
order: asc   # asc          # asc | desc | rand             (bucket modes)

print_collate_log: false       # print to stdout
wandb_collate_log:  true      # send to wandb.run.log

# --------------------------------------------------------------------- #


train:
    dataset: vb-train-16k
    dl_opts:
        pin_memory: true
        num_workers: 12 #  # 24 # 6
        shuffle: true
        # batch_size is ignored when mode=bucket_budget
        batch_size: 4 # 8 # 4 # 8 # 15 # 15 # 8 # 10  # == 40 with 4 GPUs
val:
    dataset: vb-val-16k
    dl_opts:
        pin_memory: true
        num_workers: 4
        shuffle: false
        batch_size: 1 # 1 # 8 # 4 # 1
test:
    dataset: vb-test-16k
    dl_opts:
        pin_memory: true
        num_workers: 4
        shuffle: false
        batch_size: 1

datasets:
    vb-train-16k:
        _target_: open_universe.datasets.NoisyDataset
        audio_path: data/voicebank_demand/16k
        text_path: data/voicebank_demand/trainset_28spk_txt  # NEW: path to transcript files
        # audio_path: ../../data/voicebank_demand/16k
        # text_path: ../../data/voicebank_demand/trainset_28spk_txt  # NEW: path to transcript files
        fs: 16000
        split: train
        # max clip length kept in **all** modes
        audio_len: 4.0 # UPDATE: 4 seconds
        part_used: 1.0 # 0.1 # 1.0 # 0.01  # Use only 5% of data

    vb-val-16k: # NORMAL
        _target_: open_universe.datasets.NoisyDataset
        audio_path: ${..vb-train-16k.audio_path}
        text_path: ${..vb-train-16k.text_path}  # Re-use the same text_path
        fs: ${..vb-train-16k.fs}
        split: val
        # max clip length kept in **all** modes
        audio_len: 12.0 # UPDATE: 4 seconds here too
        part_used: 1.0 # 0.1 # 1.0  # Use 20% of validation data for faster validation

    vb-test-16k:
        _target_: open_universe.datasets.NoisyDataset
        audio_path: ${..vb-train-16k.audio_path}
        text_path: ${..vb-train-16k.text_path}  # Re-use the same text_path
        fs: ${..vb-train-16k.fs}
        split: test
        # max clip length kept in **all** modes
        audio_len: 12.0 # UPDATE: 4 seconds here too
        part_used: 1.0  # Use full test set for final evaluation
