_target_: open_universe.datasets.DataModule
train:
    dataset: vb-train-16k
    dl_opts:
        pin_memory: true
        num_workers: 12 # 24 # 6
        shuffle: true
        batch_size: 8 # 8 # 15 # 15 # 8 # 10  # == 40 with 4 GPUs
val:
    dataset: vb-val-16k
    dl_opts:
        pin_memory: true
        num_workers: 4
        shuffle: false
        batch_size: 4 # 1
test:
    dataset: vb-test-16k
    dl_opts:
        pin_memory: true
        num_workers: 4
        shuffle: false
        batch_size: 1

datasets:
    vb-train-16k:
        _target_: open_universe.datasets.NoisyDataset
        audio_path: data/voicebank_demand/16k
        text_path: data/voicebank_demand/trainset_28spk_txt  # NEW: path to transcript files
        # audio_path: ../../data/voicebank_demand/16k
        # text_path: ../../data/voicebank_demand/trainset_28spk_txt  # NEW: path to transcript files
        fs: 16000
        split: train
        audio_len: 4.0 # UPDATE: 4 seconds
        part_used: 1.0 # 0.1 # 1.0 # 0.01  # Use only 5% of data

    vb-val-16k: # NORMAL
        _target_: open_universe.datasets.NoisyDataset
        audio_path: ${..vb-train-16k.audio_path}
        text_path: ${..vb-train-16k.text_path}  # Re-use the same text_path
        fs: ${..vb-train-16k.fs}
        split: val
        audio_len: 4.0 # UPDATE: 4 seconds here too
        part_used: 1.0 # 0.1 # 1.0  # Use 20% of validation data for faster validation

    vb-test-16k:
        _target_: open_universe.datasets.NoisyDataset
        audio_path: ${..vb-train-16k.audio_path}
        # text_path: ${..vb-train-16k.text_path}  # Re-use the same text_path
        fs: ${..vb-train-16k.fs}
        split: test
        audio_len: 4.0 # UPDATE: 4 seconds here too
        part_used: 1.0  # Use full test set for final evaluation
