defaults:
    - _self_
    - datamodule: default
    - model: default
    - trainer: default
    - experiment: default

seed: 46762398
# ckpt_path: null
# ckpt_path: checkpoints/universe/exper/last.ckpt
# ckpt_path: ./exp/universepp_vb_16k_NS2_wv/2025-04-12_18-31-56_/checkpoints/universe/exper/last.ckpt
ckpt_path: ./exp/universepp_vb_16k_NS2_4s/2025-04-14_11-27-04_/checkpoints/universe/exper/last.ckpt
train: true
test: false

path:
    exp_root: exp
    figures: figures
    
version_base: null
hydra:
    run:
        dir: ${path.exp_root}/${hydra.runtime.choices.experiment}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${hydra.job.override_dirname}
    job:
        config:
            override_dirname:
                kv_sep: '-'
                item_sep: '_'
                exclude_keys: 
                    - path.exp_root
                    - experiment
                    - ckpt_path



# defaults:
#     - _self_
#     - datamodule: default
#     - model: default
#     - trainer: default
#     - experiment: default

# seed: 46762398
# # ckpt_path: null
# # ckpt_path: checkpoints/universe/exper/last.ckpt
# ckpt_path: ./exp/universepp_vb_16k/2025-03-06_23-30-48_/checkpoints/universe/exper/last.ckpt
# train: true
# test: false

# path:
#     exp_root: exp
#     figures: figures
    
# version_base: null
# hydra:
#     run:
#         dir: ${path.exp_root}/${hydra.runtime.choices.experiment}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${hydra.job.override_dirname}
#     job:
#         config:
#             override_dirname:
#                 kv_sep: '-'
#                 item_sep: '_'
#                 exclude_keys: 
#                     - path.exp_root
#                     - experiment
#                     - ckpt_path
