defaults:
    - _self_
    - datamodule: default
    - model: default
    - trainer: default
    - experiment: default

seed: 46762398
# ckpt_path: null


# ckpt_path: checkpoints/universe/exper/last.ckpt
# ckpt_path: ./exp/universepp_vb_16k_NS2_wv/2025-04-12_18-31-56_/checkpoints/universe/exper/last.ckpt
# ckpt_path: ./exp/universepp_vb_16k_NS2_4s/2025-04-14_11-27-04_/checkpoints/universe/exper/last.ckpt
# ckpt_path: ./exp/universepp_vb_16k_NS2_4s/2025-04-14_23-52-51_/checkpoints/universe/exper/last.ckpt
# ckpt_path: ./exp/universepp_vb_16k_NS2_4s/2025-04-15_05-42-24_/checkpoints/universe/exper/last.ckpt
# ckpt_path: ./exp/universepp_vb_16k_plain_4s/2025-04-17_21-46-53_/checkpoints/universe/exper/last.ckpt

# ckpt_path: ./exp/universepp_vb_16k_NS2_4s/2025-04-19_09-39-26_/checkpoints/universe/exper/last.ckpt

# resume bucket_cluster
# ckpt_path: ./exp/bucket_cluster/2025-04-20_12-27-05_/checkpoints/universe/exper/last.ckpt

# ckpt_path: ./exp/orig_local/2025-04-22_08-55-23_/checkpoints/universe/exper/last.ckpt # resume orig_local model

# ckpt_path: ./exp/aligned_local/2025-04-24_18-16-05_/checkpoints/universe/exper/last.ckpt

# ckpt_path: ./exp/orig_bucket_cluster/2025-04-25_15-19-58_/checkpoints/universe/exper/last.ckpt # 27 Apr

ckpt_path: .exp/bucket_cluster/2025-04-21_17-48-19_/checkpoints/universe # 28 Apr - continue text bucket cluster run from 21 Apr


train: true
test: false

path:
    exp_root: exp
    figures: figures
    
version_base: null
hydra:
    run:
        dir: ${path.exp_root}/${hydra.runtime.choices.experiment}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${hydra.job.override_dirname}
    job:
        config:
            override_dirname:
                kv_sep: '-'
                item_sep: '_'
                exclude_keys: 
                    - path.exp_root
                    - experiment
                    - ckpt_path



# defaults:
#     - _self_
#     - datamodule: default
#     - model: default
#     - trainer: default
#     - experiment: default

# seed: 46762398
# # ckpt_path: null
# # ckpt_path: checkpoints/universe/exper/last.ckpt
# ckpt_path: ./exp/universepp_vb_16k/2025-03-06_23-30-48_/checkpoints/universe/exper/last.ckpt
# train: true
# test: false

# path:
#     exp_root: exp
#     figures: figures
    
# version_base: null
# hydra:
#     run:
#         dir: ${path.exp_root}/${hydra.runtime.choices.experiment}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${hydra.job.override_dirname}
#     job:
#         config:
#             override_dirname:
#                 kv_sep: '-'
#                 item_sep: '_'
#                 exclude_keys: 
#                     - path.exp_root
#                     - experiment
#                     - ckpt_path
