_target_: open_universe.networks.universe.Universe

fs: 16000
normalization_norm: 2
normalization_kwargs:
  ref: both  # noisy scales according to noisy signal, "both" scales separately
  level_db: -26.0

score_model:
  _target_: open_universe.networks.universe.ScoreNetwork
  fb_kernel_size: 3
  rate_factors: [2, 4, 4, 5]
  n_channels: 32
  n_rff: 32
  noise_cond_dim: 512
  encoder_gru_conv_sandwich: false
  extra_conv_block: true
  decoder_act_type: prelu
  use_weight_norm: false
  seq_model: gru
  use_antialiasing: false

condition_model:
  _target_: open_universe.networks.universe.ConditionerNetwork
  fb_kernel_size: ${model.score_model.fb_kernel_size}
  rate_factors: ${model.score_model.rate_factors}
  n_channels: ${model.score_model.n_channels}
  n_mels: 80
  n_mel_oversample: 4
  encoder_gru_residual: true
  extra_conv_block: ${model.score_model.extra_conv_block}
  decoder_act_type: prelu
  use_weight_norm: ${model.score_model.use_weight_norm}
  seq_model: ${model.score_model.seq_model}
  use_antialiasing: false

diffusion:
  schedule: geometric
  sigma_min: 5e-4
  sigma_max: 5.0
  n_steps: 8
  epsilon: 1.3

losses:
  weights:
    score: 1.0
    signal: 1.0
    latent: 1.0
  mdn_n_comp: 3
  mdn_alpha_per_sample: true
  score_loss:
    _target_: torch.nn.MSELoss

training:
  audio_len: ${datamodule.datasets.vb-train-16k.audio_len}
  time_sampling: time_uniform
  dynamic_mixing: false
  ema_decay: 0.999

validation:
  main_loss: val/pesq
  main_loss_mode: max
  n_bins: 5
  max_enh_batches: 4
  num_tb_samples: 0
  enh_losses:
    val/:
      _target_: open_universe.metrics.EvalMetrics
      audio_fs: ${model.fs}

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0002
  weight_decay: 0.01
  weight_decay_exclude: [prelu, bias]
  lr_warmup: null
  betas: [0.8, 0.99]

scheduler:
  scheduler:
    _target_: open_universe.utils.schedulers.LinearWarmupCosineAnnealingLR
    T_warmup: 50000
    T_cosine: 50001
    eta_min: 1.6e-06
    T_max: ${trainer.max_steps}
  interval: step
  frequency: 1

grad_clipper:
  _target_: open_universe.utils.FixedClipper
  max_norm: 1000.0
